#!/bin/bash
# Test script to demonstrate real-time lobby join events

echo "=================================="
echo "  Real-Time Lobby Event Test"
echo "=================================="
echo ""
echo "This test demonstrates that lobby join events now propagate in real-time"
echo ""
echo "Instructions:"
echo "1. Open poker-game-client.html in TWO browser tabs"
echo ""
echo "Tab 1 (Admin):"
echo "  - Register as 'Player1'"
echo "  - Click 'CREATE LOBBY'"
echo "  - Copy the Lobby ID"
echo "  - WATCH the messages - you'll see when Player2 joins!"
echo ""
echo "Tab 2 (Player):"
echo "  - Register as 'Player2'"
echo "  - Click 'JOIN LOBBY'"
echo "  - Paste the Lobby ID from Tab 1"
echo ""
echo "Expected Result:"
echo "  ✓ Tab 1 receives real-time notification:"
echo "    '👤 New player joined lobby (2/X players)'"
echo ""
echo "  ✓ Tab 2 sees:"
echo "    '🏠 Joined lobby - Waiting for admin to start...'"
echo ""
echo "=================================="
echo "Server Status:"
docker ps | grep aipoker-server
echo ""
echo "Server is running on ws://localhost:8081/ws/poker"
echo ""
echo "You can check server logs with:"
echo "  docker logs -f aipoker-server"
echo ""
echo "=================================="
